let _DESCS = {
  'asia-east1':              'Taiwan',
  'asia-east2':              'Hong Kong',
  'asia-northeast1':         'Tokyo, Japan',
  'asia-northeast2':         'Osaka, Japan',
  'asia-northeast3':         'Seoul, South Korea',
  'asia-south1':             'Mumbai, India',
  'asia-southeast1':         'Singapore',
  'australia-southeast1':    'Sydney, Australia',
  'europe-north1':           'Hamina, Finland',
  'europe-west1':            'Belgium',
  'europe-west2':            'London, UK',
  'europe-west3':            'Frankfurt, Germany',
  'europe-west4':            'Netherlands',
  'europe-west6':            'Zürich, Switzerland',
  'global':                  'Global HTTP Load Balancer',
  'northamerica-northeast1': 'Montréal, Canada',
  'southamerica-east1':      'São Paulo, Brazil',
  'us-central1':             'Iowa, USA',
  'us-east1':                'South Carolina, USA',
  'us-east4':                'Northern Virginia, USA',
  'us-west1':                'Oregon, USA',
  'us-west2':                'Los Angeles, USA',
  'us-west3':                'Salt Lake City, USA',
  'us-west4':                'Las Vegas, USA',
};
